### ISSUE TITLE
outdated dependency 

### ISSUE THREAD

**Issue by SeanFloresDOMO** [redbabel/loopback-component-model-diagram#6]
eslint-plugin-import is fixed at v2.2.0 which asks for eslint <3.x which is outdated.

`"dependencies": {
    "eslint-plugin-import": "2.2.0",
  },`

should be

`"dependencies": {
    "eslint-plugin-import": "^2.2.0",
  },`

**Comment by alemhnan** [comment]
Fixed, apologies for the biblical delay.
